services:
    Github\Client:
        arguments:
            - '@Github\HttpClient\Builder'
        # Uncomment to enable authentication
        calls:
            - ['authenticate', ['%env(GITHUB_USERNAME)%', '%env(GITHUB_SECRET)%', '%env(GITHUB_AUTH_METHOD)%']]

    Github\HttpClient\Builder:
        arguments:
            - '@?Http\Client\HttpClient'
            - '@?Psr\Http\Message\RequestFactoryInterface'
            - '@?Psr\Http\Message\StreamFactoryInterface'
