# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
imports:
    - { resource: '../vendor/symplify/symfony-static-dumper/config/config.yaml' }

parameters:
    social:
        github:
            username: jibbarth
        twitter:
            username: jibbarth
        linkedin:
            username: 'in/jib√©-b-772884a3'
    interests:
        - PHP
        - Symfony
        - Open Source
        - Code Quality
        - VueJS
        - Tailwind
        - Docker

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $projectDir: '%kernel.project_dir%'
            iterable $gifProviders: !tagged_iterator app.gif_provider

    _instanceof:
        App\Gif\GifLinkProviderInterface:
            tags: ['app.gif_provider']
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Repository\Article\:
        resource: '../src/Repository/Article/*'
        tags: ['app.article_repository']

    App\Repository\ChainArticleRepository:
        arguments:
            - !tagged_iterator app.article_repository
    App\Repository\ArticleRepositoryInterface: '@App\Repository\ChainArticleRepository'
