# see https://github.com/marketplace/actions/deploy-to-github-pages
name: Build and Deploy

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 */6 * * *'

jobs:
    check:
        runs-on: ubuntu-latest
        name: Validate code
        steps:
            -   name: Checkout üõéÔ∏è
                uses: actions/checkout@v2
                with:
                    persist-credentials: false
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none
            -   run: composer install --no-progress
            -   name: Grumphp
                run: vendor/bin/grumphp run --ansi
            -   name: PHPInsights
                run: vendor/bin/phpinsights -n --ansi
    deploy:
        needs: check
        runs-on: ubuntu-latest
        name: Deploy static website
        steps:
            -   name: Checkout üõéÔ∏è
                uses: actions/checkout@v2
                with:
                    persist-credentials: false
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none
            -   uses: actions/setup-node@v1
            -   run: yarn install
            -   run: yarn encore prod
            -   run: composer install --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader --no-suggest
            -   name: Build üì¶
                run: bin/console dump-static-site --ansi
                env:
                    GITHUB_USERNAME: ${{ secrets.GITHUB_TOKEN }}
            -   name: Deploy üöÄ
                uses: JamesIves/github-pages-deploy-action@releases/v3
                with:
                    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    REPOSITORY_NAME: Jibbarth/jibbarth.github.io
                    BRANCH: master
                    FOLDER: output
    update-readme:
        needs: check
        runs-on: ubuntu-latest
        name: Update Github Profile Readme
        steps:
            -   name: Checkout üõéÔ∏è
                uses: actions/checkout@v2
                with:
                    persist-credentials: false
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none
            -   uses: actions/setup-node@v1
            -   run: yarn install
            -   run: composer install --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader --no-suggest
            -   name: Build üì¶
                run: bin/console generate-readme --ansi
                env:
                    GITHUB_USERNAME: ${{ secrets.GITHUB_TOKEN }}
            -   name: Deploy üöÄ
                uses: JamesIves/github-pages-deploy-action@releases/v3
                with:
                    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    REPOSITORY_NAME: Jibbarth/Jibbarth
                    BRANCH: master
                    FOLDER: output
